pivnet_token: vd2sDF3JnEeuMzxsXVhW
#git_private_key:

opsman_major_minor_version: ^1\.12\..*$
ert_major_minor_version: ^1\.12\..*$

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable: none

# RDS Master Credentials
db_master_username: admin
db_master_password: Password123!

# ERT Database Credentials
db_app_usage_service_username: admin
db_app_usage_service_password: Password123!
db_autoscale_username: admin
db_autoscale_password: Password123!
db_diego_username: admin
db_diego_password: Password123!
db_notifications_username: admin
db_notifications_password: Password123!
db_routing_username: admin
db_routing_password: Password123!
db_uaa_username: admin
db_uaa_password: Password123!
db_ccdb_username: admin
db_ccdb_password: Password123!
db_accountdb_username: admin
db_accountdb_password: Password123!
db_networkpolicyserverdb_username: admin
db_networkpolicyserverdb_password: Password123!
db_nfsvolumedb_username: admin
db_nfsvolumedb_password: Password123!
db_silk_username: admin
db_silk_password: Password123!
db_locket_username: admin
db_locket_password: Password123!

# Prefix to use for Terraform-managed infrastructure, e.g. 'pcf-terraform'
terraform_prefix: pcftim-terraform

# Optional certificates to add to BOSH director
director_certificates:

# This key must be a key with admin access
TF_VAR_aws_access_key: AKIAID4NIHNXVIOJL6JA
TF_VAR_aws_secret_key: 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

# ARN of the wildcard certificate to use; upload this in [AWS](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html#upload-server-certificate). This must be done prior to running the pipeline.
TF_VAR_aws_cert_arn: arn:aws:iam::754058048930:server-certificate/pcftim

# AMI to use for nat box
TF_VAR_amis_nat: ami-303b1458

TF_VAR_aws_region: us-east-1
TF_VAR_az1: us-east-1b
TF_VAR_az2: us-east-1d
TF_VAR_az3: us-east-1e

# For terraform state file
S3_ENDPOINT: https://s3.amazonaws.com
S3_OUTPUT_BUCKET: pcftim-terraform

# The ERT domain to use; *.cfapps.<ert-domain> and *.sys.<ert-domain> will be used
ERT_DOMAIN: cf-training.net

# Route53 zone to add records to
ROUTE_53_ZONE_ID: Z3BYLDYCVKN7KJ

# Cert will be generated if left empty
ERT_SSL_CERT:
ERT_SSL_KEY:

haproxy_forward_tls: enable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:         # HAProxy will use the CA provided to verify the certificates provided by the router.

routing_disable_http: false

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers:         # The recommended setting is "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".
haproxy_tls_ciphers:        # The recommended setting is "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".

# The domain to access Operations Manager; opsman.<ert-domain>
opsman_domain_or_ip_address: opsman.cf-training.net

# Operations Manager credentials
OPSMAN_USER: admin
OPSMAN_PASSWORD: Password123!

# Key to use for Operations Manager, NAT VMs.
PEM: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAsks52m4HBRAAXQv9pCeAsK4lru+n4w9Z+75Ta5rVdbpqPwmxoyB9OD47XV1A
  3EG7UYMEmU6UyWShzYVropwj7xwF5+Hv0rqjU1pQYTacVvqP7fs2q3Iu4SuTdSkSgY7/aJ4XgheV
  mXBA72zGCZlMv+NxlsktaiFUt53mPFoIt977hs8ztDzo0QdLQvI3uFHbXzRZChO79eaxgcGU9HzK
  ZuxZTE3U60IQkSEgn2NVfX9tJZx+YS3f3Gbisv1YljEUSlBcZ42qg99MtBBRfuvRZKocNrAiTqAd
  nKJ+I6EqisLJlEwyXJiJCRS/IU4pi5s+92a1Q7EjhUxx0SMY9/CCxwIDAQABAoIBAB6SAXBvbyqy
  DK3nkWzlDQ6+PV3aX7nx9ubQQnNvz+vos7DtU5T5zB6ppPokNCvP5XNbeJ1kuOQzKf8YQlVWWl70
  OhsBRWKnd7uh/6g7eeD8A1O1wDDzWhBnrVfoW/D0+NwSR0uaCZ+OfMPQrcAVlfBM6jwFcJEC+Ain
  vUNZ2KbV/lNSXJI46KkHuzbcFHXt9xY6A//p4yOFIFXImkMC0VFildDIy3V6V+GKGZWYA2uuQonU
  4ZzAgz28S6h2sYGvnnKCpTDgx1YMQNF2Q9TqpCRE1AJeVQoFMXstUW7WMFlkLK1U+k+K04wwJA2I
  8ukdlXRUS/SrdJ6lhg+cXl/wF1ECgYEA6XVxjuGd0Dv+0TAkkFklGmevPfLs7p3g95XgP8trY+uz
  oz7Dhjxpz2lD8NWvRRU8pLhnsHwwMjkbuNYFy4/8oRnd87tcq5oasATjOfZqrKm2VH18uN0SStV5
  LKx+fg/xRTtCLunsdvv5SgnOge+cuFbbbGpWZyK0Cyr82/PKSHkCgYEAw4I7/1g57KMmIh82d0dt
  KGRqPab0ENCCe67wqfDLf33ApWQTIToXlHjDTbrzK2koGa/+QRxe7yz5nkLil5vyhCLSPHyT9JL6
  eLIFoIQ7xXVgiNdJtMCf5pb7d5lFdRtINYLOYO7UjUcvdFMYlE/HD9JUAlzXkvFMOZsudoK81T8C
  gYEAj9fpDBw/XFpa+xEqtjX3Ann4I7dV/QAR6PrTnPr9RCeqG19EoaT/nOhDEFTZFTusjeGBIeCi
  4Y8GYbCdCXvCMJD7jH1Y7/KXlvSr/L6zo4c97HkVK+Iqrykw7DGsDohMJFgKw1UmeXlvdAruzmiQ
  q5P4xqgObKWZQXhPLEbd0CECgYEAsOuns5h5QoUZOwOX3DTMuSK1aXktoBGwIpDaxE5dOM/ph0Ga
  dhUFxZvK0Qp+hygv258BrJYp6rJ+aRMJzjyXJ7ADJC1wDoD7HEGtCebf1/4yD2MTFfjCOn8irMYM
  rr6zh4kJjXpS6k4iyVdxBLV05AJnd4PgqN6nJfIiB6ijjS0CgYEAt2+M7GBE+4z1iFCNihSyAGZj
  gNI/g805OmFQICxnGbzLtz+CzS13x+pF10l8deSjkZsZOSioWXczOhUtektc+8afGAskmET4C9ql
  UqxQmNoikcMOYxDFyxO++OxQiEJbj8z9aMRdfqq4fYNy/3LgtIYovchA1DDIbS0kk2wexP8=
  -----END RSA PRIVATE KEY-----

# Upload PEM to AWS as the below key pair name
TF_VAR_aws_key_name: pcftim

# CIDRs to allow SSH access to Operations Manager from; configure PEM as well with the private key
opsman_allow_ssh_cidr_ranges: 0.0.0.0/0

# CIDRs to allow HTTPS access to Operations Manager from
opsman_allow_https_cidr_ranges: 0.0.0.0/0

# Email address for sending mysql monitor notifications
mysql_monitor_recipient_email: foo@bar.com

# Whether to enable MySQL backups. (disable|s3|scp)
mysql_backups: disable

# SCP backup config params (leave empty values if you're not using scp
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

# S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

# Subnets
#   Pipeline uses six types of network: Public, Elastic Runtime, Services, Dynamic Services and RDS and Infrastructure networks
#
#   * Public Network: Ops manager and Nat boxes who needs public internet accessible through internet gateway
#   * Elastic Runtime network: Cloud Foundry components, **three subnets on three AZs to achieve HA**
#   * Services network: Deploy PCF tile services, **three subnets on three AZs to achieve HA**
#   * Dynamic Services network: Deploy dynamic services, **three subnets on three AZs to achieve HA**
#   * RDS network: Deploy RDS databases, **three subnets on three AZs to achieve HA**
#   * Infrastructure network: Deploy Bosh director
TF_VAR_vpc_cidr: 192.168.0.0/16
TF_VAR_public_subnet_cidr_az1: 192.168.0.0/24
TF_VAR_public_subnet_cidr_az2: 192.168.1.0/24
TF_VAR_public_subnet_cidr_az3: 192.168.2.0/24
TF_VAR_ert_subnet_cidr_az1: 192.168.16.0/20
ert_subnet_reserved_ranges_z1: 192.168.16.0 - 192.168.16.10
TF_VAR_ert_subnet_cidr_az2: 192.168.32.0/20
ert_subnet_reserved_ranges_z2: 192.168.32.0 - 192.168.32.10
TF_VAR_ert_subnet_cidr_az3: 192.168.48.0/20
ert_subnet_reserved_ranges_z3: 192.168.48.0 - 192.168.48.10
TF_VAR_services_subnet_cidr_az1: 192.168.64.0/20
services_subnet_reserved_ranges_z1: 192.168.64.0 - 192.168.64.10
TF_VAR_services_subnet_cidr_az2: 192.168.80.0/20
services_subnet_reserved_ranges_z2: 192.168.80.0 - 192.168.80.10
TF_VAR_services_subnet_cidr_az3: 192.168.96.0/20
services_subnet_reserved_ranges_z3: 192.168.96.0 - 192.168.96.10
TF_VAR_dynamic_services_subnet_cidr_az1: 192.168.112.0/22
dynamic_services_subnet_reserved_ranges_z1: 192.168.112.0 - 192.168.112.10
TF_VAR_dynamic_services_subnet_cidr_az2: 192.168.128.0/22
dynamic_services_subnet_reserved_ranges_z2: 192.168.128.0 - 192.168.128.10
TF_VAR_dynamic_services_subnet_cidr_az3: 192.168.144.0/22
dynamic_services_subnet_reserved_ranges_z3: 192.168.144.0 - 192.168.144.10
TF_VAR_infra_subnet_cidr_az1: 192.168.6.0/24
infra_subnet_reserved_ranges_z1: 192.168.6.0 - 192.168.6.10
TF_VAR_rds_subnet_cidr_az1: 192.168.3.0/24
TF_VAR_rds_subnet_cidr_az2: 192.168.4.0/24
TF_VAR_rds_subnet_cidr_az3: 192.168.5.0/24
TF_VAR_opsman_ip_az1: 192.168.0.7
TF_VAR_nat_ip_az1: 192.168.0.6
TF_VAR_nat_ip_az2: 192.168.1.6
TF_VAR_nat_ip_az3: 192.168.2.6
