pivnet_token: vd2sDF3JnEeuMzxsXVhW
git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAtI180/z5VLFMc/LGfy+SLB+XnCJYge9m5r6j19REjRW7IKsu
  wDLUTQysL0f0kY1Ymy6lcT/mRCEBjzwBgPcBa+4vCe8pvysJn+9mNXfVwGJpdUh/
  0UUJeC9I8LA5uOlhDXUGozLYzzTzpvA1FV5vNk6t9ye5+X4otS/g27hmO3RiHgeW
  RqyYM068qC/GIm5EatSrgYuV73qZKdz1IcfMPUHThCnOnV/Ev2o1Zliww4mb95T3
  5be0rm/OLKRyL9uqq3sYH+/kdrI/c6CMrhesNhwxW3FQHD7Xzp5PJJzH6admGNnM
  z5dotTcD2EYIjQJ0kUmuSALmNYhV9O4bnT2ZsML0lzuK2K1WjTRgFeAXZ1jduAr8
  dZkPv9Agl0dt3bOCZxYSnsWvmgP6I2NdvbHzCrHZhNpK9jxcek7DC9VVAHPS3UwZ
  i9il3+MyvYtCpe+5hm8fshZYAmBNdd77SHtnZRlN7NvALgPMRj+MwzO0eJISgNVw
  fAV5GfA9JFcgziUQg/ri/YPxUbIpreaOh/YjsfthZrgLTBD7q/RBpAfWpJ+W36jC
  TWFwnYy3Azb//opYNpOskLvblLUMJWrF9TbwpD00USyYwZxgUUb9kPqAmsKfM6YU
  8cIiiequAaJiIR1fGi0C9S/j5N/sR002LGIh3v+kmj3RWp91iRG1A5QNBFMCAwEA
  AQKCAgBW4ue5VDngKdoyyhf/yLK9DQ72kgiprr2EOSW7jWjXxCdjFz3OPCeyVHDf
  5+6nxK9pLk9ramazTnbjqOrIVxWWDO8SBse+OUXOc3RqMprok/NP/22TFXfzID4n
  pYaBl72erjxdePCg9khyg5HoEKPQLJjHIZT7nVyVpM6+rcR0xBMbhGcq54/u0Os0
  vJjKpOnDx0gpdTTYI9VlMfG9Kdr9d5oENeI6FYYm30OHVxLpZmVqBYQuRfNrJl6/
  WPuiUEGXeAsqA1WcUTb7u703Yij7eSG/cY4tqYhM5B4N7my94lLdjqJjG+fFnQ36
  m+ktgor6B80Y1lxWUp++RGpoXJJieHBPPD+HMLWu0eXFaxYk2bd7TwdRfiTKS5LAgARy7fABltV892rH9/m
  coGwPEZxB7SZoBEY+3MJVN/MON3saYytVks+EErgcZiOROv89V2UEl6PYPod09o1
  F3KnJ5EdM8CqwtvP701eb4IyLzK4uhfeyvxUnuHhR2T7aRZGe7qPiEvMxgGdUZK9
  rWiahAOwUrRLRQvKBZdlSlP4xZoS39NNZ7zuN296JxJCzE62CKIZZApohCltr2Nt
  jEXgze7dpISGZIa+gc6GARF8cVHbz7E8BdI7Yi3rqv+7lelXUQKCAQEA8JUQilAx
  /lpoJXMOp1G3s2IfDv7Imc8n6OpebCH5GUkwEphTo4eXylK9u77+ypJaxuDm+Ifj
  nKAMOEEvXi6PQZvwYe61x9LjNLK7LcLqFXsMUHeS00u/apyGK84DFEO44HZ/SMtS
  +h2npPbjyBFRQOqjahvg06dYKJy3gZsGI85Pvd2XKFG0xt/kAr/Jb5pDInIfyGet
  0/FTI3jhYL4szG3/vzlBCU+qHdoBt5ZmYUkRtLzxKigtCsoIWlvmFnJhyV6USTy/
  wKAv6hNEvXcFzD+LYoWf676ajMllnL2L1WvR3W74cGFGqWrCtTYhDuPoC5TCeYG0
  TZ8o4XdxX6nlnwKCAQEAwB+XfvjymuMc78IwZatY+u5/n5WBHkHeCJ1CTVZ9BJ/T
  Dp7Hf9fRilCYkJjdrIhcq4P2PqvJ3FtCD+/QrUh4mcsp6Au6hb9NjH82DV1srX8g
  w7b3PR3RkwjfJD16+JDWreHw0jeXnsVj8feOXc20cqBtD79IzxHYAUIpH42uuegE
  DDSSogcA2VKKhRt4bi2MB7vKaVKtOqqHwUtkVJQpTJFyQh2Viugeq/w7DCE9A/po
  9GSTdrHF2IPGQtgisVyqsbw1GGT4EOusnfaKIrFpAUg28l+R4KJ8wvm5CQphVSKk
  QEzXQR3HIqSV851soKUoTz3vP9pMO1NyWOVyNaVczQKCAQEAiNdw8gtNdGy+Alcg
  haFgiOMN4XygY4RGIiB1FrJ4Op67fkgwgrqUZxuLGig4SsbWZXr1RXYdzC/o43KI
  W9zF1T66iym5MfDNFWN4Pj444YD87yQkWpUiSqS/WFk0vSkMFniwS5qDFwsZGSbp
  Rxo6il8sFiXHSvxLk8YYRtsDsggeqVNKMD/RQLGGwt2N2TH4b7ZUR6xZXk1Mycdv
  ApUJbDpBFuadDIvIqnQfN+qPT1S9gn1Z+22guRtThvnwtOHYpy5p0AKC2zECL/VH
  yzDRFm0qfh6daP0gcWX4qx/RUtKiK358R4e9Jo44M9SXFx4hFb1GpNBW2zPlj+Fd
  lllP5wKCAQAEqr/LXdDG4m15hYYXciofLlv7TG5uhbsXCnrp1ggDbL57xG+kM2Hr
  sjmCibQY1Ncrc3Ev5Ixqxey85l5zVydW1RCXinFlflgr6Ysul+5j6IqrNm6bFXZZ
  1AVXpAawsxQD9VEcSi1ste7Pmevja3POtQbxMvxZy10r6qeFFLQB4Bj5Eu3c8b6b
  iN3Ejf5G7uRP68fm9xMuMaZKk8JEK7U1HvNfl8hiL3FPTDlC+iu5RQP3q9nJMFhW
  Ah120jlFhbK/zoqbpRhBkPgIfkysuxKJ7W8oRBoPEuNk+Rv9lDr5DnZe+X7hHhAQ
  T181I8XXwStRgXemXW8socJNVoWHuBShAoIBAQDh4jVIa/E3E+2jW9NVakiSC+fx
  cpkpuPQ1CZp4gi34SzwC8SJSvqWursGT/3cZQrtfIs6IxkXOIAXC/3ZHieasWxoG
  onwQazPJhABj4DrAcfFT/gA3Cbl8n5WKgnivU5/qmA3ygANCC0eESe9NvOmko26/
  X8yu8aPl3ktcM7P015bcGzjOGmYO2B6CShgbjIouZWgolq/B/DgGKIgYuiMpKPc3
  /SKNVl/uGWzhwpcLNIz/YllQREzVGY89L0rigyIn3W9JykrCQizIxquwYXN9Q4YM
  ftINiPaEdefuy8cOE3dZXzxHDR04brAIbHpFSxzIW8J/IqmjhZ8qpci3Mklb
  -----END RSA PRIVATE KEY-----

opsman_major_minor_version: ^1\.12\..*$
ert_major_minor_version: ^1\.12\..*$

# Errands to disable prior to deploying ERT
# Valid values:
#   all
#   none
#   "" (empty string)
#   Any combination of the following, separated by comma:
#     smoke-tests
#     push-apps-manager
#     notifications
#     notifications-ui
#     push-pivotal-account
#     autoscaling
#     autoscaling-register-broker
#     nfsbrokerpush
ert_errands_to_disable: none

# RDS Master Credentials
db_master_username:
db_master_password:

# ERT Database Credentials
db_app_usage_service_username:
db_app_usage_service_password:
db_autoscale_username:
db_autoscale_password:
db_diego_username:
db_diego_password:
db_notifications_username:
db_notifications_password:
db_routing_username:
db_routing_password:
db_uaa_username:
db_uaa_password:
db_ccdb_username:
db_ccdb_password:
db_accountdb_username:
db_accountdb_password:
db_networkpolicyserverdb_username:
db_networkpolicyserverdb_password:
db_nfsvolumedb_username:
db_nfsvolumedb_password:
db_silk_username:
db_silk_password:
db_locket_username:
db_locket_password:

# Prefix to use for Terraform-managed infrastructure, e.g. 'pcf-terraform'
terraform_prefix: pcftim-terraform

# Optional certificates to add to BOSH director
director_certificates:

# This key must be a key with admin access
TF_VAR_aws_access_key: AKIAID4NIHNXVIOJL6JA
TF_VAR_aws_secret_key: 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

# ARN of the wildcard certificate to use; upload this in [AWS](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html#upload-server-certificate). This must be done prior to running the pipeline.
TF_VAR_aws_cert_arn: arn:aws:iam::754058048930:server-certificate/pcftim

# AMI to use for nat box
TF_VAR_amis_nat: ami-303b1458

TF_VAR_aws_region: us-east-1
TF_VAR_az1: us-east-1b
TF_VAR_az2: us-east-1d
TF_VAR_az3: us-east-1e

# For terraform state file
S3_ENDPOINT: https://s3.amazonaws.com
S3_OUTPUT_BUCKET: pcftim-terraform

# The ERT domain to use; *.cfapps.<ert-domain> and *.sys.<ert-domain> will be used
ERT_DOMAIN: cf-training.net

# Route53 zone to add records to
ROUTE_53_ZONE_ID: cf-training.net

# Cert will be generated if left empty
ERT_SSL_CERT:
ERT_SSL_KEY:

haproxy_forward_tls: enable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:         # HAProxy will use the CA provided to verify the certificates provided by the router.

routing_disable_http: false

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers:         # The recommended setting is "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".
haproxy_tls_ciphers:        # The recommended setting is "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".

# The domain to access Operations Manager; opsman.<ert-domain>
opsman_domain_or_ip_address:

# Operations Manager credentials
OPSMAN_USER:
OPSMAN_PASSWORD:

# Key to use for Operations Manager, NAT VMs.
PEM:
# Upload PEM to AWS as the below key pair name
TF_VAR_aws_key_name:

# CIDRs to allow SSH access to Operations Manager from; configure PEM as well with the private key
opsman_allow_ssh_cidr_ranges:

# CIDRs to allow HTTPS access to Operations Manager from
opsman_allow_https_cidr_ranges:

# Email address for sending mysql monitor notifications
mysql_monitor_recipient_email:

# Whether to enable MySQL backups. (disable|s3|scp)
mysql_backups: disable

# SCP backup config params (leave empty values if you're not using scp
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

# S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

# Subnets
#   Pipeline uses six types of network: Public, Elastic Runtime, Services, Dynamic Services and RDS and Infrastructure networks
#
#   * Public Network: Ops manager and Nat boxes who needs public internet accessible through internet gateway
#   * Elastic Runtime network: Cloud Foundry components, **three subnets on three AZs to achieve HA**
#   * Services network: Deploy PCF tile services, **three subnets on three AZs to achieve HA**
#   * Dynamic Services network: Deploy dynamic services, **three subnets on three AZs to achieve HA**
#   * RDS network: Deploy RDS databases, **three subnets on three AZs to achieve HA**
#   * Infrastructure network: Deploy Bosh director
TF_VAR_vpc_cidr: 192.168.0.0/16
TF_VAR_public_subnet_cidr_az1: 192.168.0.0/24
TF_VAR_public_subnet_cidr_az2: 192.168.1.0/24
TF_VAR_public_subnet_cidr_az3: 192.168.2.0/24
TF_VAR_ert_subnet_cidr_az1: 192.168.16.0/20
ert_subnet_reserved_ranges_z1: 192.168.16.0 - 192.168.16.10
TF_VAR_ert_subnet_cidr_az2: 192.168.32.0/20
ert_subnet_reserved_ranges_z2: 192.168.32.0 - 192.168.32.10
TF_VAR_ert_subnet_cidr_az3: 192.168.48.0/20
ert_subnet_reserved_ranges_z3: 192.168.48.0 - 192.168.48.10
TF_VAR_services_subnet_cidr_az1: 192.168.64.0/20
services_subnet_reserved_ranges_z1: 192.168.64.0 - 192.168.64.10
TF_VAR_services_subnet_cidr_az2: 192.168.80.0/20
services_subnet_reserved_ranges_z2: 192.168.80.0 - 192.168.80.10
TF_VAR_services_subnet_cidr_az3: 192.168.96.0/20
services_subnet_reserved_ranges_z3: 192.168.96.0 - 192.168.96.10
TF_VAR_dynamic_services_subnet_cidr_az1: 192.168.112.0/22
dynamic_services_subnet_reserved_ranges_z1: 192.168.112.0 - 192.168.112.10
TF_VAR_dynamic_services_subnet_cidr_az2: 192.168.128.0/22
dynamic_services_subnet_reserved_ranges_z2: 192.168.128.0 - 192.168.128.10
TF_VAR_dynamic_services_subnet_cidr_az3: 192.168.144.0/22
dynamic_services_subnet_reserved_ranges_z3: 192.168.144.0 - 192.168.144.10
TF_VAR_infra_subnet_cidr_az1: 192.168.6.0/24
infra_subnet_reserved_ranges_z1: 192.168.6.0 - 192.168.6.10
TF_VAR_rds_subnet_cidr_az1: 192.168.3.0/24
TF_VAR_rds_subnet_cidr_az2: 192.168.4.0/24
TF_VAR_rds_subnet_cidr_az3: 192.168.5.0/24
TF_VAR_opsman_ip_az1: 192.168.0.7
TF_VAR_nat_ip_az1: 192.168.0.6
TF_VAR_nat_ip_az2: 192.168.1.6
TF_VAR_nat_ip_az3: 192.168.2.6
